language: go

go:
  - tip # The latest version of Go.

install: true

env:
  global:
    - MYAPP=drawio
    - COMMIT=${TRAVIS_COMMIT::7}

before_install:
  - sudo apt-get -qq update

services:
  - docker

install:
  - go get -u github.com/mmkhitaryan/$MYAPP
  - cd $GOPATH/src/github.com/mmkhitaryan/$MYAPP
  - go install
  - mkdir -p build/linux
  - GOOS=linux GOARCH=amd64 go build -o build/linux/$MYAPP *.go
  - ls -la
  - ls -la build/linux/
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export DRAWIO=allinse/drawio
  - docker build -t $DRAWIO:$COMMIT .
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag $DRAWIO:$COMMIT $DRAWIO:$TAG
  - docker push $DRAWIO

script: echo "good passed"